<a href="https://colab.research.google.com/github/MayukhBanerjee/Heart-Disease-Predictor/blob/main/Heart_Disease_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv("heart_disease_data.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
#separating features and target variables
X = df.drop(columns = ["target"])
y = df["target"]

In [ ]:
#defining categorical and numerical terms
cat_data = ["sex" , "cp", "restecg" , "slope", "thal"]
num_data = ["age", "trestbps" , "chol" , "thalach" , "oldpeak" ,"ca"]

In [ ]:
numerical_transformer = MinMaxScaler()
categorical_transformer = OneHotEncoder(drop='first', sparse=False)
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, num_data),
        ('cat', categorical_transformer, cat_data)
    ])

In [39]:
X_processed = preprocessor.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [40]:
#now on applying the regression model we get:

model = LogisticRegression(max_iter = 1000 , random_state = 42)

#training
model.fit(X_train, y_train)

#predictions on the testing set
y_pred = model.predict(X_test)

#calculating accuracy
accuracy = accuracy_score(y_test , y_pred)
print("Accuracy : ", accuracy)

Accuracy :  0.9016393442622951

In [41]:
X_test_indexed = pd.DataFrame(X_test, index=y_test.index)

# Add a new column 'predicted_target' to the DataFrame
X_test_indexed['predicted_target'] = y_pred
pred_df = df.merge(X_test_indexed, left_index=True, right_index=True)
print(pred_df)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  ...  \
5     57    1   0       140   192    0        1      148      0      0.4  ...
7     44    1   1       120   263    0        1      173      0      0.0  ...
9     57    1   2       150   168    0        1      174      0      1.6  ...
17    66    0   3       150   226    0        1      114      0      2.6  ...
24    40    1   3       140   199    0        1      178      1      1.4  ...
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...  ...
283   40    1   0       152   223    0        1      181      0      0.0  ...
284   61    1   0       140   207    0        0      138      1      1.9  ...
285   46    1   0       140   311    0        1      120      1      1.8  ...
292   58    0   0       170   225    1        0      146      1      2.8  ...
300   68    1   0       144   193    1        1      141      0      3.4  ...

       8    9   10   11   12   13   14   15   16  predicted_target
5    0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0                 0
7    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0                 1
9    1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0                 1
17   0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0                 1
24   0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0                 1
..   ...  ...  ...  ...  ...  ...  ...  ...  ...               ...
283  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0                 0
284  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0                 0
285  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0                 0
292  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0                 0
300  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0                 0

[61 rows x 32 columns]

In [43]:
# Define the filename for the CSV file
output_filename = "updated_dataframe.csv"
pred_df.to_csv(output_filename, index=False)
print("DataFrame has been saved as:", output_filename)

DataFrame has been saved as: updated_dataframe.csv